CREATE TABLE [dbo].[Task]
(
	TaskId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Title NVARCHAR(255) NOT NULL,
	Description NVARCHAR(MAX) NULL,
	IsCompleted BIT NOT NULL DEFAULT 0,
	DueDate DATETIME NULL,
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE(),
	UserId UNIQUEIDENTIFIER NOT NULL,

	CONSTRAINT FK_Tasks_Users FOREIGN KEY (UserId) REFERENCES dbo.[User](UserId)
)
