CREATE TABLE [dbo].[User]
(
	UserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	UserName NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL,
	PasswordHash NVARCHAR(255) NOT NULL, 
	CreatedDate DATETIME NOT NULL DEFAULT GETDATE()
)
